### PR TITLE
Support for ROS kinetic

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by jgoppert** [comment]
This gets the guidance working on ros kinetic and ubuntu 16.04.

**Comment by jgoppert** [comment]
@tangketan Is anything holding back this PR? I would like to get it merged if possible.

**Comment by tangketan** [comment]
Hi, thanks for the PR. I didn't just merge it because I wanted to test it myself. However I didn't get time during last days. Now it seems there are some conflicts with the main branch. Do you think it possible to fix the conflicts? Thanks a lot!

**Comment by jgoppert** [comment]
@tangketan I fixed the conflicts.

**Comment by jgoppert** [comment]
A lot of these changes are just white space. Going forward we should make sure all contributions have uniform white space handling. I'm using astyle to format here with no tabs and 4 spaces.

**Comment by nickpotts** [comment]
Hi, I'm sorry to just drop in here; however, I have a proposal I want to get out to someone at DJI.  I'm currently a Junior in High School and for an IT project we want to create a drone that can be controlled with hand gestures that are read by an Xbox 360 kinect.  We already have the hand tracking software up and running and we have a DJI Phantom 2 Vision+ drone with remote. Would it be possible to convert  the Eular Angles read by the kinetic to inputs the remote controller would be able to read? Then send those inputs to the drone? Thank you

**Comment by lanyusea** [comment]
@nickpotts  please refer to the document of Mobile SDK

**Pull request merged**
